export const users = [
  {
    userName: "josh",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "angela",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "bran",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "dennis",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "josh",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "angela",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "bran",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "dennis",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "josh",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "angela",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "bran",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "dennis",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "josh",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "angela",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "bran",
    newMessage: "",
    date: "",
    notifications: "",
  },
  {
    userName: "dennis",
    newMessage: "",
    date: "",
    notifications: "",
  },
];
